export const wizardCopy = {
  en: {
    eyebrow: 'Hong Kong company setup',
    pageTitle: 'Start your company registration enquiry',
    pageIntro: 'Answer a few focused questions. WINFO will review your situation and contact you with the practical next step.',
    steps: [
      { title: 'What would you like to call your company?', text: 'Share up to three name ideas in order of preference. Availability is confirmed only after an official search.' },
      { title: 'Tell us about the founders', text: 'This helps us understand the likely structure and document route.' },
      { title: 'A little about the business', text: 'A short, plain-language description is enough for the first review.' },
      { title: 'Which support would help?', text: 'Select any areas you would like us to discuss. These choices are not a final quotation.' },
      { title: 'How should we contact you?', text: 'We only need general contact details at this stage. Please do not upload or enter identity or banking records.' },
      { title: 'Review your enquiry', text: 'Check the details below. You can return to any section before sending.' },
    ],
    progress: { step: 'Step', of: 'of', complete: 'complete' },
    actions: { back: 'Back', continue: 'Continue', submit: 'Send enquiry', sending: 'Sending enquiry', exit: 'Exit and return to WINFO', edit: 'Edit' },
    fields: {
      companyNames: 'Preferred company name', companyNamePlaceholder: 'Name option', decideNameLater: 'I will decide the company name later',
      profile: 'Founder profile', directors: 'Number of directors', shareholders: 'Number of shareholders',
      business: 'What will the business do?', businessPlaceholder: 'For example: technology consulting for clients in Hong Kong and overseas',
      timing: 'When would you like to begin?', existingCompany: 'Do you already have a Hong Kong company?',
      services: 'Support to discuss', needsAddress: 'Registered address and mail handling', needsBanking: 'Bank account preparation', needsCompliance: 'Bookkeeping, audit and tax consultation', noService: 'No additional support selected yet',
      name: 'Your name', contact: 'Phone number or email', message: 'Anything else we should know?', messagePlaceholder: 'Optional — a short note is enough',
      consent: 'I agree that WINFO may use these details to respond to my enquiry, as explained in the', privacy: 'Privacy policy',
    },
    profiles: { local: 'Hong Kong founder', mainland: 'Mainland founder', undecided: 'Other / not sure yet' },
    timings: { asap: 'As soon as possible', 'within-month': 'Within one month', 'within-three-months': 'Within three months', researching: 'I am still comparing options' },
    existingOptions: { no: 'No', yes: 'Yes', unsure: 'Not sure' },
    countOptions: ['1', '2', '3', '4', '5', '6+'],
    validation: 'Please complete the highlighted information before continuing.',
    required: 'Required', optional: 'Optional',
    summary: { title: 'Your enquiry summary', empty: 'Your answers will appear here as you go.', names: 'Company name', founders: 'Founder profile', structure: 'Proposed structure', business: 'Business', timing: 'Timing', existing: 'Existing company', services: 'Support requested', contact: 'Contact', later: 'To be decided later' },
    reassurance: 'No payment is taken here. A WINFO adviser will review the enquiry before confirming scope, fees or documents.',
    draft: 'Your progress is saved in this browser tab.',
    success: { title: 'Your enquiry is on its way.', text: 'Thank you. WINFO will review the general information and contact you through the details provided.', home: 'Return to WINFO', whatsapp: 'Message us on WhatsApp' },
    failure: { title: 'The form could not be sent just now.', text: 'Your answers are still saved in this browser tab. Please retry or use WhatsApp or email so we do not miss your enquiry.', retry: 'Try again', whatsapp: 'Use WhatsApp instead', email: 'Email WINFO' },
  },
  'zh-Hant': {
    eyebrow: '香港公司成立',
    pageTitle: '由這裡開始，整理你的公司註冊需要',
    pageIntro: '用幾分鐘回答幾個重點問題，WINFO 會先了解你的情況，再與你確認最實際的下一步。',
    steps: [
      { title: '你心目中的公司名稱是甚麼？', text: '可按心水次序填寫最多三個名稱；最終能否使用，仍須以正式查冊結果為準。' },
      { title: '說說創辦團隊的情況', text: '這些資料有助我們初步判斷公司架構及文件準備方向。' },
      { title: '讓我們先了解業務方向', text: '第一次查詢不用寫得複雜，用自己的話簡單說明即可。' },
      { title: '還需要哪些成立支援？', text: '可選擇希望一併了解的服務；這裡只收集意向，並非最終報價。' },
      { title: '留下方便聯絡你的方式', text: '現階段只需一般聯絡資料，請勿填寫身份證明、銀行紀錄或其他敏感資料。' },
      { title: '核對資料，安心送出', text: '送出前再看一遍；如要調整，可返回任何一個部分修改。' },
    ],
    progress: { step: '步驟', of: '／', complete: '已完成' },
    actions: { back: '返回', continue: '繼續', submit: '送出查詢', sending: '正在送出', exit: '離開並返回 WINFO', edit: '修改' },
    fields: {
      companyNames: '心儀公司名稱', companyNamePlaceholder: '名稱選項', decideNameLater: '公司名稱稍後再決定',
      profile: '創辦人身份', directors: '董事人數', shareholders: '股東人數',
      business: '公司主要會經營甚麼業務？', businessPlaceholder: '例如：為香港及海外客戶提供科技顧問服務',
      timing: '希望何時開始？', existingCompany: '目前是否已有香港公司？',
      services: '希望一併了解的服務', needsAddress: '註冊地址及郵件代收', needsBanking: '銀行開戶資料準備', needsCompliance: '記帳、審計及報稅諮詢', noService: '暫未選擇其他支援',
      name: '你的稱呼', contact: '電話號碼或電郵', message: '還有甚麼想讓我們先知道？', messagePlaceholder: '選填；簡單說明即可',
      consent: '我同意 WINFO 按照以下政策使用這些資料回覆我的查詢：', privacy: '私隱政策',
    },
    profiles: { local: '香港本地創業者', mainland: '內地創業者', undecided: '其他／仍在考慮' },
    timings: { asap: '希望盡快開始', 'within-month': '一個月內', 'within-three-months': '三個月內', researching: '仍在比較不同方案' },
    existingOptions: { no: '沒有', yes: '有', unsure: '尚未確定' },
    countOptions: ['1', '2', '3', '4', '5', '6+'],
    validation: '請先完成標示的資料，再繼續下一步。',
    required: '必填', optional: '選填',
    summary: { title: '你的查詢摘要', empty: '完成選項後，資料會逐步顯示在這裡。', names: '公司名稱', founders: '創辦人身份', structure: '預計架構', business: '業務方向', timing: '開始時間', existing: '現有公司', services: '所需支援', contact: '聯絡方式', later: '稍後決定' },
    reassurance: '這裡不會收取任何款項。WINFO 顧問會先審閱查詢，再確認服務範圍、費用及所需文件。',
    draft: '填寫進度會暫存在目前的瀏覽器分頁。',
    success: { title: '查詢已順利送出。', text: '多謝你提供資料。WINFO 會先了解整體情況，再按你留下的方式與你聯絡。', home: '返回 WINFO', whatsapp: '透過 WhatsApp 聯絡' },
    failure: { title: '表格暫時未能送出。', text: '你的答案仍保存在目前的瀏覽器分頁。可重試一次，或改用 WhatsApp／電郵聯絡我們。', retry: '重新送出', whatsapp: '改用 WhatsApp', email: '電郵聯絡 WINFO' },
  },
  'zh-Hans': {
    eyebrow: '香港公司成立',
    pageTitle: '从这里开始，梳理你的公司注册需求',
    pageIntro: '用几分钟回答几个重点问题，WINFO 会先了解你的情况，再与你确认最实际的下一步。',
    steps: [
      { title: '你心目中的公司名称是什么？', text: '可按心仪顺序填写最多三个名称；最终能否使用，仍须以正式查册结果为准。' },
      { title: '说说创办团队的情况', text: '这些资料有助于我们初步判断公司架构及文件准备方向。' },
      { title: '让我们先了解业务方向', text: '第一次咨询不用写得复杂，用自己的话简单说明即可。' },
      { title: '还需要哪些成立支持？', text: '可选择希望一并了解的服务；这里仅收集意向，并非最终报价。' },
      { title: '留下方便联系你的方式', text: '现阶段只需一般联系资料，请勿填写身份证明、银行记录或其他敏感资料。' },
      { title: '核对资料，安心提交', text: '提交前再看一遍；如需调整，可返回任何一个部分修改。' },
    ],
    progress: { step: '步骤', of: '／', complete: '已完成' },
    actions: { back: '返回', continue: '继续', submit: '提交查询', sending: '正在提交', exit: '离开并返回 WINFO', edit: '修改' },
    fields: {
      companyNames: '心仪公司名称', companyNamePlaceholder: '名称选项', decideNameLater: '公司名称稍后再决定',
      profile: '创办人身份', directors: '董事人数', shareholders: '股东人数',
      business: '公司主要会经营什么业务？', businessPlaceholder: '例如：为香港及海外客户提供科技咨询服务',
      timing: '希望何时开始？', existingCompany: '目前是否已有香港公司？',
      services: '希望一并了解的服务', needsAddress: '注册地址及邮件代收', needsBanking: '银行开户资料准备', needsCompliance: '记账、审计及报税咨询', noService: '暂未选择其他支持',
      name: '你的称呼', contact: '电话号码或邮箱', message: '还有什么想让我们先知道？', messagePlaceholder: '选填；简单说明即可',
      consent: '我同意 WINFO 按照以下政策使用这些资料回复我的咨询：', privacy: '隐私政策',
    },
    profiles: { local: '香港本地创业者', mainland: '内地创业者', undecided: '其他／仍在考虑' },
    timings: { asap: '希望尽快开始', 'within-month': '一个月内', 'within-three-months': '三个月内', researching: '仍在比较不同方案' },
    existingOptions: { no: '没有', yes: '有', unsure: '尚未确定' },
    countOptions: ['1', '2', '3', '4', '5', '6+'],
    validation: '请先完成标示的资料，再继续下一步。',
    required: '必填', optional: '选填',
    summary: { title: '你的查询摘要', empty: '完成选项后，资料会逐步显示在这里。', names: '公司名称', founders: '创办人身份', structure: '预计架构', business: '业务方向', timing: '开始时间', existing: '现有公司', services: '所需支持', contact: '联系方式', later: '稍后决定' },
    reassurance: '这里不会收取任何款项。WINFO 顾问会先审核查询，再确认服务范围、费用及所需文件。',
    draft: '填写进度会暂存在当前浏览器标签页。',
    success: { title: '查询已顺利提交。', text: '感谢你提供资料。WINFO 会先了解整体情况，再按你留下的方式与你联系。', home: '返回 WINFO', whatsapp: '通过 WhatsApp 联系' },
    failure: { title: '表格暂时未能提交。', text: '你的答案仍保存在当前浏览器标签页。可重试一次，或改用 WhatsApp／邮箱联系我们。', retry: '重新提交', whatsapp: '改用 WhatsApp', email: '邮件联系 WINFO' },
  },
};
