import { useState } from 'react';
import { formatPrice, getContent, getExtendedContent, getUi, pricingData, toSimplified } from '../content/site';
import { Icon, LinkButton, consultationUrl } from '../components/SiteShell';
import { Breadcrumb, Checklist, ConsultationPanel, FAQ, FinalCta, ProcessList, RegisteredAddressSection, RegistrationInquiry, SectionHeading, TestimonialSection } from '../components/Sections';

export function IncorporationPage({ navigate, kind = 'local', language }) {
  const page = getContent(language).incorporation[kind];
  const extended = getExtendedContent(language);
  const copy = getUi(language);
  const isMainland = kind === 'mainland';
  const localize = (value) => language === 'zh-Hans' ? toSimplified(value) : value;
  const [needsAddress, setNeedsAddress] = useState(false);
  const basePrice = isMainland ? pricingData.mainland : pricingData.local;
  const planLabel = isMainland ? copy.priceMainlandLabel : copy.priceLocalLabel;
  const included = language === 'en' ? ['Initial company-name check', 'Company structure information', 'Incorporation document preparation and filing coordination', 'Company secretarial arrangement', 'SCR / designated representative arrangement', 'Digital or physical handover of agreed company documents'] : localize(['公司名稱初步查核', '公司架構資料整理', '成立文件準備及提交協調', '公司秘書安排', 'SCR／指定代表安排', '電子或實體公司文件交付']);
  const excluded = language === 'en' ? ['Final bank-account approval', 'Bookkeeping, audit and tax filing', 'Special licences or regulated-industry applications', 'Courier, translation, notarisation and certification', 'Complex shareholding or legal advice'] : localize(['銀行開戶最終審批', '會計記帳、審計及報稅', '特別牌照或受規管行業申請', '快遞、翻譯、公證及認證', '複雜股權及法律意見']);
  const receive = language === 'en' ? ['Certificate of incorporation', 'Business registration certificate', 'Articles and agreed company documents', 'Next compliance and renewal reminders'] : localize(['公司註冊證明書', '商業登記證', '公司章程及已確認方案內的公司文件', '後續合規與續費提醒']);
  const bankItems = language === 'en' ? ['Basic company and director/shareholder information', 'Business plan, customer or supplier information', 'Source of funds and expected transaction pattern', 'Additional evidence requested by the bank'] : ['公司及董事股東基本資料', '業務計劃、客戶或供應商資料', '資金來源及預計交易安排', '按銀行要求補充的證明文件'];
  return <>
    <section className="detail-hero"><div className="container"><Breadcrumb current={page.crumb} navigate={navigate} language={language} /><div className="detail-hero-grid"><div><p className="hero-kicker">{language === 'en' ? 'Company setup' : '公司成立服務'}</p><h1>{page.title}</h1><p>{page.lead}</p><div className="hero-actions"><a className="button" href={consultationUrl(`${planLabel} ${formatPrice(basePrice)}`, language)} target="_blank" rel="noreferrer">{copy.priceEnquiry} <Icon name="arrow" size={16} /></a><LinkButton to="#documents" navigate={navigate} className="button-secondary">{page.secondary}</LinkButton></div></div><aside className="price-hero-card"><span>{planLabel}</span><strong>{formatPrice(basePrice)}</strong><p>{copy.priceDetails}</p><a className="price-addon-link" href="#registered-address">{copy.priceAddressShort} <Icon name="arrow" size={15} /></a></aside></div></div></section>
    <section className="section"><div className="container two-column"><SectionHeading label={copy.suitableFor} title={copy.suitableTitle} /><Checklist items={page.fit} dark /></div></section>
    <section className="section soft-band"><div className="container"><SectionHeading label={copy.serviceScope} title={copy.serviceTitle} text={copy.scopeText} /><div className="included-grid"><article><h3>{copy.include}</h3><Checklist dark items={included} /></article><article><h3>{copy.exclude}</h3><Checklist dark items={excluded} /></article><article><h3>{copy.receive}</h3><Checklist dark items={receive} /></article></div></div></section>
    <section id="documents" className="section"><div className="container documents-layout"><SectionHeading label={copy.documents} title={isMainland ? (language === 'en' ? 'Mainland-founder document checklist' : '內地人士文件清單') : (language === 'en' ? 'Prepare these details first' : '開始前先備好這些資料')} text={language === 'en' ? 'Use general documents for the initial review. Sensitive information is collected only through a confirmed secure channel.' : '請先以一般文件作初步評估；敏感資料會在確認安全收集安排後再提交。'} /><Checklist items={page.documents} dark /></div></section>
    <RegistrationInquiry language={language} kind={kind} needsAddress={needsAddress} setNeedsAddress={setNeedsAddress} />
    <section className="section process-section"><div className="container process-layout"><SectionHeading label={language === 'en' ? 'Four steps' : '四步流程'} title={language === 'en' ? 'Know what is being handled at every step.' : '每一步都知道正在處理甚麼。'} /><ProcessList items={page.process} /></div></section>
    {isMainland && <section className="section bank-section"><div className="container bank-grid"><div><span className="section-label">{copy.bankPreparation}</span><h2>{copy.bankTitle}</h2><p>{copy.bankText}</p></div><Checklist items={bankItems} /></div></section>}
    <section className="section timeline-section"><div className="container"><SectionHeading label={copy.postSetup} title={copy.postTitle} /><div className="timeline"><article><span>{language === 'en' ? 'After incorporation' : '成立後'}</span><h3>{language === 'en' ? 'Company secretarial and statutory records' : '公司秘書及法定記錄'}</h3><p>{language === 'en' ? 'Maintain company information, statutory records and secretarial arrangements as applicable.' : '按適用規定維持公司資料、法定記錄及公司秘書安排。'}</p></article><article><span>{copy.annual}</span><h3>{language === 'en' ? 'Annual return and business registration' : '周年申報及商業登記'}</h3><p>{language === 'en' ? 'Handle annual returns, renewals and related government documents as required.' : '按要求處理周年申報、續期及相關政府文件。'}</p></article><article><span>{copy.ongoing}</span><h3>{language === 'en' ? 'Bookkeeping, audit and tax' : '記帳、審計及報稅'}</h3><p>{language === 'en' ? 'Arrange financial records, audit and tax work according to transactions and statutory requirements.' : '按公司交易及法定要求安排財務記錄、審計與稅務處理。'}</p></article></div></div></section>
    <FAQ items={page.faqs} title={language === 'en' ? 'Company setup questions' : '成立公司常見問題'} language={language} />
    <TestimonialSection language={language} testimonials={extended.testimonials} compact serviceType={isMainland ? 'mainland' : 'local'} />
    <ConsultationPanel navigate={navigate} language={language} topic={page.primary} title={language === 'en' ? 'Want to confirm your setup route?' : '想先確認你的公司成立方案？'} />
    <RegisteredAddressSection language={language} kind={kind} checked={needsAddress} setChecked={setNeedsAddress} />
    <FinalCta language={language} title={language === 'en' ? 'Ready to start your Hong Kong business?' : '準備好，開始你的香港業務？'} text={language === 'en' ? 'Tell us your profile, ownership structure and intended start date. We will organise the most practical first step.' : '先說明你的身份、公司架構及希望開始的時間，我們會整理最合適的第一步。'} topic={page.primary} />
  </>;
}
