import { useState } from 'react';
import { getExtendedContent, getUi } from '../content/site';
import { Icon, LinkButton, consultationUrl } from './SiteShell';

export function Breadcrumb({ current, navigate, language }) { const copy = getUi(language); return <div className="breadcrumb"><button type="button" onClick={() => navigate('/')}>{copy.home}</button><span>/</span><span>{current}</span></div>; }
export function SectionHeading({ label, title, text, light = false }) { return <div className={`section-heading ${light ? 'light' : ''}`}><span className="section-label">{label}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
export function FAQ({ items, title, language }) { const [open, setOpen] = useState(0); const copy = getUi(language); return <section className="section faq-band"><div className="container faq-layout"><SectionHeading label={copy.faq} title={title || copy.faqTitle} /><div className="faq-list">{items.map(([question, answer], index) => <article key={question} className={open === index ? 'faq-item open' : 'faq-item'}><button type="button" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span>{question}</span><Icon name="chevron" size={20} /></button><div className="faq-answer"><p>{answer}</p></div></article>)}</div></div></section>; }
export function FinalCta({ title, text, topic, language }) { const copy = getUi(language); return <section className="final-cta"><div className="container final-cta-inner"><div><h2>{title || copy.setUpTitle}</h2><p>{text || copy.setUpText}</p></div><a className="button button-light" href={consultationUrl(topic || copy.initialConsultation, language)} target="_blank" rel="noreferrer">{copy.whatsappEnquiry} <Icon name="arrow" size={16} /></a></div></section>; }
export function ProcessList({ items, compact = false }) { return <ol className={`process-list ${compact ? 'compact' : ''}`}>{items.map(([number, title, text]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><Icon name="arrow" size={20} /></li>)}</ol>; }
export function Checklist({ items, dark = false }) { return <ul className={`checklist ${dark ? 'dark' : ''}`}>{items.map((item) => <li key={item}><Icon name="check" size={18} /><span>{item}</span></li>)}</ul>; }
export function ConsultationPanel({ title, text, topic, navigate, language, documentsTarget = '#documents' }) { const copy = getUi(language); return <section id="consultation" className="consultation-panel"><div className="container consultation-grid"><div><span className="section-label">{copy.initialConsultation}</span><h2>{title || copy.consultationTitle}</h2><p>{text || copy.consultationText}</p></div><div className="consultation-actions"><a className="button" href={consultationUrl(topic || copy.initialConsultation, language)} target="_blank" rel="noreferrer">{copy.whatsappEnquiry} <Icon name="arrow" size={16} /></a><LinkButton to={documentsTarget} navigate={navigate} className="button-secondary">{copy.viewDocuments}</LinkButton><small>{copy.noSensitive}</small></div></div></section>; }

export function TestimonialSection({ language, testimonials, compact = false }) {
  const copy = getUi(language);
  return <section className={`section testimonial-section ${compact ? 'testimonial-compact' : ''}`}><div className="container"><div className="testimonial-heading"><div><span className="section-label">{copy.testimonialLabel}</span><h2>{copy.testimonialHeading}</h2></div><div className="rating-mark" aria-label={`${copy.ratingLabel}: ${copy.ratingValue}`}><strong>{copy.ratingValue}</strong><span>{copy.ratingLabel}</span></div></div><div className="testimonial-grid">{testimonials.map((item) => <blockquote key={item.name}><p>“{item.quote}”</p><footer><strong>{item.name}</strong><span>{item.context}</span></footer></blockquote>)}</div><p className="testimonial-note">{getExtendedContent(language).ratingNote}</p></div></section>;
}

export function RegistrationInquiry({ language, kind = 'local' }) {
  const copy = getUi(language);
  const [form, setForm] = useState({ profile: kind === 'mainland' ? copy.mainland : copy.local, needAddress: copy.no });
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = (event) => { event.preventDefault(); const details = Object.entries(form).filter(([, value]) => value).map(([key, value]) => `${key}: ${value}`).join('\n'); window.open(consultationUrl(`${copy.registrationInquiry}\n${details}`, language), '_blank', 'noopener,noreferrer'); };
  return <section className="section inquiry-section" id="registration-inquiry"><div className="container inquiry-layout"><div><SectionHeading label={copy.registrationInquiry} title={copy.setUpTitle} text={copy.registrationIntro} /><p className="form-note">{copy.noSensitive}</p></div><form className="inquiry-form" onSubmit={submit}><label>{copy.name}<input name="name" value={form.name || ''} onChange={update} required /></label><label>{copy.contactMethod}<input name="contact" value={form.contact || ''} onChange={update} required /></label><label>{copy.companyNames}<input name="companyNames" placeholder={copy.companyNamesPlaceholder} value={form.companyNames || ''} onChange={update} /></label><label>{copy.business}<input name="business" value={form.business || ''} onChange={update} /></label><label>{copy.profile}<select name="profile" value={form.profile} onChange={update}><option>{copy.local}</option><option>{copy.mainland}</option><option>{copy.other}</option></select></label><label>{copy.needAddress}<select name="needAddress" value={form.needAddress} onChange={update}><option>{copy.yes}</option><option>{copy.no}</option></select></label><label>{copy.directors}<input name="directors" value={form.directors || ''} onChange={update} /></label><button className="button" type="submit">{copy.submitInquiry} <Icon name="arrow" size={16} /></button></form></div></section>;
}
