import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const languages = [
  { code: 'en', label: 'EN' },
  { code: 'zh-TW', label: '繁' },
  { code: 'zh-CN', label: '简' },
];

const serviceItems = [
  { id: 'company-setup', icon: 'building', key: 'companySetup', group: 'start' },
  { id: 'accounting-audit', icon: 'ledger', key: 'accountingAudit', group: 'compliance' },
  { id: 'funding-grants', icon: 'spark', key: 'fundingGrants', group: 'grow' },
  { id: 'iang', icon: 'passport', key: 'iang', group: 'start' },
  { id: 'cross-border', icon: 'globe', key: 'crossBorder', group: 'grow' },
  { id: 'listed-company', icon: 'chart', key: 'listedCompany', group: 'grow' },
];

const finderCopy = {
  en: { title: 'Not sure where to start?', body: 'Choose the situation closest to yours and we will point you to a useful first conversation.', options: ['I am starting in Hong Kong', 'I need to stay compliant', 'I want to grow across borders', 'I am planning my IANG move'], result: 'A useful starting point', cta: 'Explore recommended service' },
  'zh-TW': { title: '不確定應該從哪裡開始？', body: '選擇最接近你情況的一項，我們會帶你到最有用的第一個對話。', options: ['我準備在香港開始', '我需要處理公司合規', '我想拓展跨境業務', '我正在規劃 IANG 落地'], result: '建議由此開始', cta: '查看推薦服務' },
  'zh-CN': { title: '不确定应该从哪里开始？', body: '选择最接近你情况的一项，我们会带你到最有用的第一个对话。', options: ['我准备在香港开始', '我需要处理公司合规', '我想拓展跨境业务', '我正在规划 IANG 落地'], result: '建议从这里开始', cta: '查看推荐服务' },
};

const finderOptions = [
  { id: 'company-setup', key: 'start' },
  { id: 'accounting-audit', key: 'compliance' },
  { id: 'cross-border', key: 'grow' },
  { id: 'iang', key: 'iang' },
];

const copy = {
  en: {
    nav: { services: 'Services', pricing: 'Pricing', cases: 'Cases', approach: 'Our approach', about: 'About', contact: 'Contact', cta: 'Book a consultation', menu: 'Menu', close: 'Close' },
    menu: { start: 'Start in Hong Kong', compliance: 'Stay compliant', grow: 'Grow across borders', explore: 'Explore all services', support: 'Need help choosing a service?', talk: 'Talk to an advisor' },
    brand: 'WINFO BUSINESS SOLUTIONS LTD.',
    hero: { title: 'Start, run and grow your business in Hong Kong.', body: 'Clear advice. Practical execution. One trusted team for company setup, compliance and cross-border growth.', primary: 'Book a consultation', secondary: 'Explore services', note: 'Built for founders, operators and cross-border teams.', visualLabel: 'HONG KONG / BUSINESS OPERATIONS', visualTitle: 'A clearer way forward.', visualText: 'From first registration to the next market, we make the complicated parts easier to move through.' },
    proof: ['Company setup', 'Accounting & audit', 'Funding & grants', 'IANG one-stop service'],
    home: { servicesKicker: 'WHAT WE DO', servicesTitle: 'The right support for every stage.', servicesBody: 'Choose the service that matches your next decision. We keep the scope clear, the process visible and the advice practical.', viewAll: 'View all services', whyKicker: 'WHY WINFO', whyTitle: 'Good decisions need more than a checklist.', whyBody: 'We combine Hong Kong operating knowledge with cross-border execution so you can move with confidence, not guesswork.', principles: ['A clear scope before work begins', 'Practical steps your team can act on', 'One accountable point of contact'], casesKicker: 'SELECTED OUTCOMES', casesTitle: 'Built around real business decisions.', casesBody: 'A framework for the work behind the headline: entering a market, securing funding, staying compliant and scaling with control.', casesButton: 'See case studies', quote: 'WINFO helped us turn a complicated Hong Kong setup into a sequence of decisions our team could actually manage.', quoteBy: 'Founder, cross-border consumer business', finalTitle: 'Ready to make the next move clearer?', finalBody: 'Tell us where you are today. We will help map the most useful next step.', finalButton: 'Start a conversation' },
    services: { kicker: 'SERVICES', title: 'Business support, made easier to act on.', body: 'A complete service framework for founders and cross-border teams. Start with one need or bring us the whole picture.', featured: 'FEATURED SERVICE', all: 'ALL SERVICES', path: 'View service', iangTitle: 'Hong Kong IANG one-stop service', iangBody: 'A practical landing plan for graduates and professionals building their next chapter in Hong Kong.', iangTag: 'New service' },
    servicePage: { back: 'All services', overview: 'SERVICE OVERVIEW', process: 'HOW IT WORKS', included: 'WHAT IS INCLUDED', ready: 'Ready to discuss your situation?', readyBody: 'We can help you understand the scope, timeline and documents before you commit.', enquire: 'Make an enquiry', placeholder: 'Detailed service content will be added here. The page structure, process steps and enquiry path are ready for your team to complete.' },
    pricing: { kicker: 'PRICING', title: 'Clear scope. Clearer costs.', body: 'Pricing frameworks are ready for your final service fees. Compare the shape of each engagement and start with a conversation.', note: 'Indicative structure. Final pricing depends on scope, company profile and current requirements.', plans: [{ name: 'Start', desc: 'For founders preparing to enter Hong Kong.', items: ['Company setup planning', 'Registration coordination', 'Initial banking guidance'], action: 'Discuss Start' }, { name: 'Operate', desc: 'For teams that need reliable ongoing compliance.', items: ['Annual compliance calendar', 'Accounting and audit coordination', 'Company secretary support'], action: 'Discuss Operate', featured: true }, { name: 'Grow', desc: 'For companies expanding across markets.', items: ['Funding and grant mapping', 'Cross-border growth planning', 'Strategic execution support'], action: 'Discuss Grow' }] },
    cases: { kicker: 'CASES', title: 'The work behind the outcome.', body: 'Use this page for concise proof: the starting point, the decisions made and the result achieved.', filters: ['All', 'Start', 'Comply', 'Grow'], projects: [{ type: 'Start', title: 'From first idea to a Hong Kong operating base', body: 'A structured setup path for a mainland founder entering Hong Kong for the first time.', result: 'Clearer launch sequence' }, { type: 'Comply', title: 'A compliance rhythm for a growing team', body: 'A practical annual framework that makes recurring filings and finance work easier to manage.', result: 'Fewer last-minute decisions' }, { type: 'Grow', title: 'Turning a funding opportunity into an executable plan', body: 'A grant-readiness and market expansion roadmap for a business preparing its next phase.', result: 'A plan the team could act on' }] },
    approach: { kicker: 'OUR APPROACH', title: 'Clarity first. Momentum next.', body: 'We make complex work easier to understand, easier to own and easier to move forward.', steps: [{ n: '01', title: 'Understand', body: 'We map your situation, constraints and the decision you are trying to make.' }, { n: '02', title: 'Structure', body: 'We turn the moving parts into a clear scope, sequence and set of responsibilities.' }, { n: '03', title: 'Execute', body: 'We coordinate the practical work and keep you informed at the points that matter.' }, { n: '04', title: 'Build on it', body: 'We leave you with a stronger operating rhythm for the next stage.' }] },
    about: { kicker: 'ABOUT WINFO', title: 'A steady partner for ambitious business moves.', body: 'WINFO Business Solutions brings together Hong Kong business services, financial perspective and cross-border execution. We help serious builders make informed decisions and turn them into practical action.', stats: [{ value: 'HK', label: 'Based in Hong Kong' }, { value: '01', label: 'Accountable team' }, { value: '360°', label: 'Business view' }], valuesTitle: 'How we work with you', values: ['We say what is clear and what still needs checking.', 'We keep advice connected to the decision in front of you.', 'We make the next step visible before we close the current one.'] },
    contact: { kicker: 'CONTACT', title: 'Tell us what you are building.', body: 'Share a few details and our team will come back with a practical starting point.', form: { name: 'Your name', email: 'Work email', company: 'Company name', message: 'What would you like help with?', send: 'Send enquiry', success: 'Thanks. Your enquiry has been recorded for follow-up.' }, detailsTitle: 'WINFO BUSINESS SOLUTIONS LTD.', address: 'Rm 122, Liven House, 61-63 King Yip Street, Kwun Tong, Kowloon, Hong Kong', email: 'enquiry@winfo.hk', phone: '+852 6651 5286', hours: 'Monday to Friday, 9:00 am to 6:00 pm' },
    privacy: { kicker: 'LEGAL', title: 'Privacy policy', updated: 'Last updated: 4 September 2026', intro: 'WINFO Business Solutions Ltd. respects your privacy. This policy explains how we collect, use, retain and protect personal data when you visit this website or contact us.', sections: [{ title: '1. Data controller and scope', body: 'WINFO Business Solutions Ltd. is responsible for personal data collected through this website and related enquiries. This policy applies to website visitors, prospective clients and people who communicate with us through the contact channels shown on this site.' }, { title: '2. Personal data we collect', body: 'We may collect your name, company name, email address, telephone number, enquiry details, communication records and basic technical information such as browser type, device information and pages visited. Please do not send identity documents or other sensitive information through the general enquiry form unless we specifically request it through an appropriate channel.' }, { title: '3. How we use data', body: 'We use personal data to respond to enquiries, provide requested information, assess and deliver services, maintain business records, improve this website, prevent misuse and comply with legal or regulatory obligations. We do not sell personal data.' }, { title: '4. Disclosure and processors', body: 'We may share relevant information with professional advisers, technology and hosting providers, payment or communication providers, government bodies or other service providers where reasonably necessary for the purposes above. Service providers are expected to handle data only for authorised purposes and with appropriate safeguards.' }, { title: '5. Retention and security', body: 'We retain personal data only for as long as reasonably necessary for the relevant purpose, legal obligations, dispute resolution and proper business records. We use reasonable administrative, technical and organisational measures to protect data, but no internet transmission or storage system can be guaranteed to be completely secure.' }, { title: '6. Your rights and enquiries', body: 'Under Hong Kong\'s Personal Data (Privacy) Ordinance, you may request access to and correction of personal data held about you, subject to applicable requirements and exemptions. To make a data access or correction request, contact enquiry@winfo.hk. We may need to verify your identity before responding.' }, { title: '7. Cookies and third-party links', body: 'This website may use essential technologies needed for operation and limited analytics or embedded services if enabled. Third-party websites linked from this site have their own privacy practices, and you should review their policies before providing information.' }, { title: '8. Changes to this policy', body: 'We may update this policy when our services, technology or legal obligations change. The latest version will be posted on this page with its update date.' }] },
    notFound: { kicker: '404', title: 'This page is not available.', body: 'The link may be out of date, or the page may still be being prepared. Let us get you back to a useful place.', home: 'Back to home', contact: 'Contact WINFO' },
    footer: { line: 'For people building across Hong Kong and beyond.', services: 'Services', company: 'Company', legal: 'Legal', privacy: 'Privacy policy', copyright: 'WINFO Business Solutions Ltd. All rights reserved.' },
  },
  'zh-TW': {
    nav: { services: '服務', pricing: '價格方案', cases: '案例', approach: '我們的方式', about: '關於我們', contact: '聯絡', cta: '預約諮詢', menu: '選單', close: '關閉' },
    menu: { start: '在香港開始事業', compliance: '穩妥處理合規', grow: '拓展跨境業務', explore: '查看全部服務', support: '不確定應該從哪裡開始？', talk: '與顧問對話' },
    brand: 'WINFO 盈豐商業有限公司',
    hero: { title: '在香港開始、經營，再把事業拓展出去。', body: '清晰建議，務實執行。由公司成立、合規管理到跨境發展，由同一支可靠團隊陪你前進。', primary: '預約諮詢', secondary: '查看服務', note: '為創業者、營運團隊及跨境企業而設。', visualLabel: '香港 / 商業營運', visualTitle: '讓下一步更清楚。', visualText: '由首次註冊到下一個市場，我們把複雜環節整理成可執行的步驟。' },
    proof: ['公司成立', '會計與審計', '資助與基金', 'IANG 一條龍服務'],
    home: { servicesKicker: '我們的服務', servicesTitle: '每個階段，都有合適的支援。', servicesBody: '按你下一個決定選擇服務。我們讓範圍清楚、流程透明、建議務實。', viewAll: '查看全部服務', whyKicker: '為什麼選擇 WINFO', whyTitle: '做好決定，不只是列出清單。', whyBody: '我們結合香港營運經驗與跨境執行能力，讓你不用靠猜，也能有把握地前進。', principles: ['開始前先確認清晰範圍', '團隊可以直接採取的實際步驟', '由同一位負責人跟進'], casesKicker: '精選成果', casesTitle: '圍繞真正的商業決定而建立。', casesBody: '由進入市場、申請資助，到持續合規和有序擴張，為每個關鍵決定建立清晰框架。', casesButton: '查看案例', quote: 'WINFO 把複雜的香港落地工作，整理成團隊真正可以掌握的一連串決定。', quoteBy: '跨境消費品牌創辦人', finalTitle: '準備好讓下一步更清楚嗎？', finalBody: '告訴我們你現在的情況，我們一起整理最有用的下一步。', finalButton: '開始對話' },
    services: { kicker: '服務範圍', title: '讓企業支援更容易理解，也更容易執行。', body: '為創業者和跨境團隊準備的完整服務框架。你可以從一項需要開始，也可以把整體情況交給我們。', featured: '重點服務', all: '全部服務', path: '查看服務', iangTitle: '香港 IANG 一條龍服務', iangBody: '為畢業生和專業人士準備的香港落地方案，支援你在香港開展下一個階段。', iangTag: '新增服務' },
    servicePage: { back: '全部服務', overview: '服務概覽', process: '服務流程', included: '服務包括', ready: '準備好討論你的情況嗎？', readyBody: '在你決定之前，我們可以先協助你了解範圍、時間和所需文件。', enquire: '提交查詢', placeholder: '詳細服務內容將會補充。頁面結構、流程步驟和查詢入口已經準備好。' },
    pricing: { kicker: '價格方案', title: '範圍清楚，費用更清楚。', body: '價格框架已準備好，待補充最終服務費用。先了解不同合作方式，再從一次對話開始。', note: '以上為參考結構，最終費用會按服務範圍、公司背景和實際要求確認。', plans: [{ name: '起步', desc: '適合準備進入香港的創業者。', items: ['公司成立規劃', '註冊流程協調', '初步銀行開戶指引'], action: '了解起步方案' }, { name: '營運', desc: '適合需要穩定處理日常合規的團隊。', items: ['年度合規日程', '會計與審計協調', '公司秘書支援'], action: '了解營運方案', featured: true }, { name: '拓展', desc: '適合正在拓展多個市場的企業。', items: ['資助與基金規劃', '跨境發展規劃', '策略執行支援'], action: '了解拓展方案' }] },
    cases: { kicker: '案例', title: '成果背後，是一套清楚的工作方法。', body: '用這個頁面整理起點、關鍵決定和最後成果，讓潛在客戶更快理解你的專業價值。', filters: ['全部', '起步', '合規', '拓展'], projects: [{ type: '起步', title: '由第一個想法到香港營運基地', body: '為首次進入香港的內地創業者，整理一套清晰的落地步驟。', result: '啟動順序更清楚' }, { type: '合規', title: '為成長中的團隊建立合規節奏', body: '以實際年度框架整理定期申報和財務工作，減少臨急決定。', result: '減少最後一刻的工作' }, { type: '拓展', title: '把資助機會變成可執行計劃', body: '為準備下一階段的企業整理申請條件、執行路線和市場拓展方向。', result: '團隊可以直接行動' }] },
    approach: { kicker: '我們的方式', title: '先把事情說清楚，再讓它向前走。', body: '讓複雜工作更容易理解、更容易分工，也更容易持續推進。', steps: [{ n: '01', title: '了解', body: '先整理你的情況、限制，以及你真正需要作出的決定。' }, { n: '02', title: '組織', body: '把各個環節整理成清晰範圍、次序和責任。' }, { n: '03', title: '執行', body: '協調實際工作，在重要節點讓你掌握進度。' }, { n: '04', title: '延伸', body: '留下更穩定的營運節奏，支援下一個階段。' }] },
    about: { kicker: '關於 WINFO', title: '陪伴認真建設事業的人，穩定走好每一步。', body: 'WINFO 盈豐商業有限公司結合香港企業服務、金融視角和跨境執行能力，協助認真建設事業的人作出清楚決定，再把決定落實成實際行動。', stats: [{ value: 'HK', label: '立足香港' }, { value: '01', label: '專責團隊' }, { value: '360°', label: '整體視角' }], valuesTitle: '我們如何與你合作', values: ['清楚說明已知事項，也標明仍需確認的部分。', '把建議連結到你眼前真正要作出的決定。', '在完成當前工作前，先讓下一步變得可見。'] },
    contact: { kicker: '聯絡我們', title: '告訴我們，你正在建設什麼。', body: '分享幾項基本資料，我們會帶著實際的起點回覆你。', form: { name: '你的姓名', email: '工作電郵', company: '公司名稱', message: '你希望我們協助什麼？', send: '提交查詢', success: '謝謝，你的查詢已記錄，我們會跟進。' }, detailsTitle: 'WINFO 盈豐商業有限公司', address: '香港九龍觀塘敬業街 61-63 號利維大廈 1 樓 122 室', email: 'enquiry@winfo.hk', phone: '+852 6651 5286', hours: '星期一至五，上午 9 時至下午 6 時' },
    privacy: { kicker: '法律資訊', title: '私隱政策', updated: '最後更新：2026 年 9 月 4 日', intro: 'WINFO 盈豐商業有限公司尊重你的私隱。本政策說明當你瀏覽本網站或與我們聯絡時，我們如何收集、使用、保留和保障個人資料。', sections: [{ title: '1. 資料控制者及適用範圍', body: 'WINFO 盈豐商業有限公司負責處理透過本網站及相關查詢收集的個人資料。本政策適用於網站訪客、潛在客戶，以及透過本網站聯絡方式與我們溝通的人士。' }, { title: '2. 我們收集的個人資料', body: '我們可能收集你的姓名、公司名稱、電郵地址、電話號碼、查詢內容、通訊記錄，以及瀏覽器類型、裝置資料和瀏覽頁面等基本技術資料。除非我們透過合適渠道特別要求，請不要在一般查詢表格提交身分證明文件或其他敏感資料。' }, { title: '3. 資料的使用方式', body: '我們會使用個人資料回覆查詢、提供你要求的資料、評估及提供服務、保存業務記錄、改善網站、防止濫用，以及履行法律或監管責任。我們不會出售個人資料。' }, { title: '4. 披露資料及服務供應商', body: '在合理需要的情況下，我們可能向專業顧問、網站及技術服務供應商、付款或通訊服務商、政府機構，或其他協助我們提供服務的供應商披露相關資料。服務供應商只可按授權目的處理資料，並應採取適當保障措施。' }, { title: '5. 保留及保安', body: '我們只會在相關目的、法律責任、爭議處理及妥善業務記錄所需期間保留個人資料。我們會採取合理的行政、技術及組織措施保障資料，但任何互聯網傳送或儲存系統均不能保證絕對安全。' }, { title: '6. 你的權利及查詢', body: '根據香港《個人資料（私隱）條例》，你可在適用要求及豁免規定下，要求查閱及更正我們持有的個人資料。如要提出查閱或更正要求，請電郵至 enquiry@winfo.hk。我們可能需要先核實你的身分。' }, { title: '7. Cookie 及第三方連結', body: '本網站可能使用運作所需的基本技術，以及在啟用時使用有限分析工具或嵌入式服務。由本網站連結至的第三方網站有其自己的私隱安排，你應在提供資料前查閱相關政策。' }, { title: '8. 政策修改', body: '當我們的服務、技術或法律責任有變化時，可能更新本政策。最新版本會連同更新日期在本頁公布。' }] },
    notFound: { kicker: '404', title: '這個頁面暫時不存在。', body: '連結可能已經更新，或頁面仍在準備中。先回到有用的地方。', home: '返回首頁', contact: '聯絡 WINFO' },
    footer: { line: '為在香港及更遠地方建設事業的人而設。', services: '服務', company: '公司', legal: '法律資訊', privacy: '私隱政策', copyright: 'WINFO 盈豐商業有限公司。版權所有。' },
  },
  'zh-CN': {
    nav: { services: '服务', pricing: '价格方案', cases: '案例', approach: '我们的方式', about: '关于我们', contact: '联系', cta: '预约咨询', menu: '菜单', close: '关闭' },
    menu: { start: '在香港开始事业', compliance: '稳妥处理合规', grow: '拓展跨境业务', explore: '查看全部服务', support: '不确定应该从哪里开始？', talk: '与顾问对话' },
    brand: 'WINFO 盈丰商业有限公司',
    hero: { title: '在香港开始、经营，再把事业拓展出去。', body: '清晰建议，务实执行。从公司成立、合规管理到跨境发展，由同一支可靠团队陪你前进。', primary: '预约咨询', secondary: '查看服务', note: '为创业者、运营团队及跨境企业而设。', visualLabel: '香港 / 商业运营', visualTitle: '让下一步更清楚。', visualText: '从首次注册到下一个市场，我们把复杂环节整理成可执行的步骤。' },
    proof: ['公司成立', '会计与审计', '资助与基金', 'IANG 一条龙服务'],
    home: { servicesKicker: '我们的服务', servicesTitle: '每个阶段，都有合适的支持。', servicesBody: '按你下一个决定选择服务。我们让范围清楚、流程透明、建议务实。', viewAll: '查看全部服务', whyKicker: '为什么选择 WINFO', whyTitle: '做好决定，不只是列出清单。', whyBody: '我们结合香港运营经验与跨境执行能力，让你不用靠猜，也能有把握地前进。', principles: ['开始前先确认清晰范围', '团队可以直接采取的实际步骤', '由同一位负责人跟进'], casesKicker: '精选成果', casesTitle: '围绕真正的商业决定而建立。', casesBody: '从进入市场、申请资助，到持续合规和有序扩张，为每个关键决定建立清晰框架。', casesButton: '查看案例', quote: 'WINFO 把复杂的香港落地工作，整理成团队真正可以掌握的一连串决定。', quoteBy: '跨境消费品牌创始人', finalTitle: '准备好让下一步更清楚吗？', finalBody: '告诉我们你现在的情况，我们一起整理最有用的下一步。', finalButton: '开始对话' },
    services: { kicker: '服务范围', title: '让企业支持更容易理解，也更容易执行。', body: '为创业者和跨境团队准备的完整服务框架。你可以从一项需要开始，也可以把整体情况交给我们。', featured: '重点服务', all: '全部服务', path: '查看服务', iangTitle: '香港 IANG 一条龙服务', iangBody: '为毕业生和专业人士准备的香港落地方案，支持你在香港开展下一个阶段。', iangTag: '新增服务' },
    servicePage: { back: '全部服务', overview: '服务概览', process: '服务流程', included: '服务包括', ready: '准备好讨论你的情况吗？', readyBody: '在你决定之前，我们可以先协助你了解范围、时间和所需文件。', enquire: '提交咨询', placeholder: '详细服务内容将会补充。页面结构、流程步骤和咨询入口已经准备好。' },
    pricing: { kicker: '价格方案', title: '范围清楚，费用更清楚。', body: '价格框架已经准备好，待补充最终服务费用。先了解不同合作方式，再从一次对话开始。', note: '以上为参考结构，最终费用会按服务范围、公司背景和实际要求确认。', plans: [{ name: '起步', desc: '适合准备进入香港的创业者。', items: ['公司成立规划', '注册流程协调', '初步银行开户指引'], action: '了解起步方案' }, { name: '运营', desc: '适合需要稳定处理日常合规的团队。', items: ['年度合规日程', '会计与审计协调', '公司秘书支持'], action: '了解运营方案', featured: true }, { name: '拓展', desc: '适合正在拓展多个市场的企业。', items: ['资助与基金规划', '跨境发展规划', '策略执行支持'], action: '了解拓展方案' }] },
    cases: { kicker: '案例', title: '成果背后，是一套清楚的工作方法。', body: '用这个页面整理起点、关键决定和最终成果，让潜在客户更快理解你的专业价值。', filters: ['全部', '起步', '合规', '拓展'], projects: [{ type: '起步', title: '从第一个想法到香港运营基地', body: '为首次进入香港的内地创业者，整理一套清晰的落地步骤。', result: '启动顺序更清楚' }, { type: '合规', title: '为成长中的团队建立合规节奏', body: '以实际年度框架整理定期申报和财务工作，减少临急决定。', result: '减少最后一刻的工作' }, { type: '拓展', title: '把资助机会变成可执行计划', body: '为准备下一阶段的企业整理申请条件、执行路线和市场拓展方向。', result: '团队可以直接行动' }] },
    approach: { kicker: '我们的方式', title: '先把事情说清楚，再让它向前走。', body: '让复杂工作更容易理解、更容易分工，也更容易持续推进。', steps: [{ n: '01', title: '了解', body: '先整理你的情况、限制，以及你真正需要作出的决定。' }, { n: '02', title: '组织', body: '把各个环节整理成清晰范围、次序和责任。' }, { n: '03', title: '执行', body: '协调实际工作，在重要节点让你掌握进度。' }, { n: '04', title: '延伸', body: '留下更稳定的运营节奏，支持下一个阶段。' }] },
    about: { kicker: '关于 WINFO', title: '陪伴认真建设事业的人，稳定走好每一步。', body: 'WINFO 盈丰商业有限公司结合香港企业服务、金融视角和跨境执行能力，协助认真建设事业的人作出清楚决定，再把决定落实成实际行动。', stats: [{ value: 'HK', label: '立足香港' }, { value: '01', label: '专责团队' }, { value: '360°', label: '整体视角' }], valuesTitle: '我们如何与你合作', values: ['清楚说明已知事项，也标明仍需确认的部分。', '把建议连接到你眼前真正要作出的决定。', '在完成当前工作前，先让下一步变得可见。'] },
    contact: { kicker: '联系我们', title: '告诉我们，你正在建设什么。', body: '分享几项基本资料，我们会带着实际的起点回复你。', form: { name: '你的姓名', email: '工作邮箱', company: '公司名称', message: '你希望我们协助什么？', send: '提交咨询', success: '谢谢，你的咨询已记录，我们会跟进。' }, detailsTitle: 'WINFO 盈丰商业有限公司', address: '香港九龙观塘敬业街 61-63 号利维大厦 1 楼 122 室', email: 'enquiry@winfo.hk', phone: '+852 6651 5286', hours: '星期一至五，上午 9 时至下午 6 时' },
    privacy: { kicker: '法律信息', title: '隐私政策', updated: '最后更新：2026 年 9 月 4 日', intro: 'WINFO 盈丰商业有限公司尊重你的隐私。本政策说明当你浏览本网站或与我们联系时，我们如何收集、使用、保留和保护个人资料。', sections: [{ title: '1. 数据控制者及适用范围', body: 'WINFO 盈丰商业有限公司负责处理通过本网站及相关咨询收集的个人资料。本政策适用于网站访客、潜在客户，以及通过本网站联系方式与我们沟通的人士。' }, { title: '2. 我们收集的个人资料', body: '我们可能收集你的姓名、公司名称、邮箱地址、电话号码、咨询内容、通信记录，以及浏览器类型、设备资料和浏览页面等基本技术资料。除非我们通过合适渠道特别要求，请不要在一般咨询表格提交身份证明文件或其他敏感资料。' }, { title: '3. 资料的使用方式', body: '我们会使用个人资料回复咨询、提供你要求的资料、评估及提供服务、保存业务记录、改善网站、防止滥用，以及履行法律或监管责任。我们不会出售个人资料。' }, { title: '4. 披露资料及服务供应商', body: '在合理需要的情况下，我们可能向专业顾问、网站及技术服务供应商、付款或通讯服务商、政府机构，或其他协助我们提供服务的供应商披露相关资料。服务供应商只可按授权目的处理资料，并应采取适当保障措施。' }, { title: '5. 保留及安全', body: '我们只会在相关目的、法律责任、争议处理及妥善业务记录所需期间保留个人资料。我们会采取合理的行政、技术及组织措施保障资料，但任何互联网传送或储存系统均不能保证绝对安全。' }, { title: '6. 你的权利及咨询', body: '根据香港《个人资料（隐私）条例》，你可在适用要求及豁免规定下，要求查阅及更正我们持有的个人资料。如要提出查阅或更正要求，请电邮至 enquiry@winfo.hk。我们可能需要先核实你的身份。' }, { title: '7. Cookie 及第三方链接', body: '本网站可能使用运行所需的基本技术，以及在启用时使用有限分析工具或嵌入式服务。由本网站链接至的第三方网站有其自己的隐私安排，你应在提供资料前查阅相关政策。' }, { title: '8. 政策修改', body: '当我们的服务、技术或法律责任有变化时，可能更新本政策。最新版本会连同更新日期在本页公布。' }] },
    notFound: { kicker: '404', title: '这个页面暂时不存在。', body: '链接可能已经更新，或页面仍在准备中。先回到有用的地方。', home: '返回首页', contact: '联系 WINFO' },
    footer: { line: '为在香港及更远地方建设事业的人而设。', services: '服务', company: '公司', legal: '法律信息', privacy: '隐私政策', copyright: 'WINFO 盈丰商业有限公司。版权所有。' },
  },
};

const serviceContent = {
  companySetup: { en: { name: 'Company setup & banking', summary: 'A clear starting point for registering and operating a Hong Kong company.', detail: 'Plan the right structure, coordinate the setup steps and understand the practical banking path before you begin.', items: ['Company structure and registration planning', 'Registered address and company secretary coordination', 'Corporate bank account preparation and guidance', 'Company changes and selected add-on services'], process: ['Share your business profile', 'Confirm the structure and documents', 'Coordinate registration and banking steps', 'Hand over a clear operating checklist'] }, 'zh-TW': { name: '公司成立與銀行開戶', summary: '為在香港成立及營運公司，準備一個清晰的起點。', detail: '由架構規劃到註冊流程，再到銀行開戶，先理解實際路線，再開始執行。', items: ['公司架構及註冊規劃', '註冊地址及公司秘書協調', '公司銀行戶口準備及指引', '公司資料變更及指定增值服務'], process: ['分享你的業務背景', '確認架構及所需文件', '協調註冊及銀行開戶步驟', '交付清晰的營運清單'] }, 'zh-CN': { name: '公司成立与银行开户', summary: '为在香港成立和运营公司，准备一个清晰的起点。', detail: '从架构规划到注册流程，再到银行开户，先理解实际路径，再开始执行。', items: ['公司架构及注册规划', '注册地址及公司秘书协调', '公司银行账户准备及指引', '公司资料变更及指定增值服务'], process: ['分享你的业务背景', '确认架构和所需文件', '协调注册及银行开户步骤', '交付清晰的运营清单'] } },
  accountingAudit: { en: { name: 'Accounting, audit & tax', summary: 'Keep recurring compliance work clear, timely and easier to manage.', detail: 'Build an annual rhythm around accounting, audit, profits tax filing, company secretarial and MPF requirements.', items: ['Bookkeeping and financial record coordination', 'Licensed accountant audit and profits tax filing', 'Company secretary and annual return support', 'MPF administration guidance'], process: ['Review your current records', 'Map deadlines and responsibilities', 'Coordinate the required professional work', 'Keep the next compliance point visible'] }, 'zh-TW': { name: '會計、審計與稅務', summary: '讓定期合規工作清晰、準時，也更容易管理。', detail: '圍繞會計、審計、利得稅報稅、公司秘書和強積金要求，建立全年工作節奏。', items: ['帳目及財務記錄協調', '持牌會計師審計及利得稅報稅', '公司秘書及周年申報支援', '強積金行政指引'], process: ['檢視你現有的財務記錄', '整理期限及責任分工', '協調所需的專業工作', '讓下一個合規節點清楚可見'] }, 'zh-CN': { name: '会计、审计与税务', summary: '让定期合规工作清晰、准时，也更容易管理。', detail: '围绕会计、审计、利得税报税、公司秘书和强积金要求，建立全年工作节奏。', items: ['账目及财务记录协调', '持牌会计师审计及利得税报税', '公司秘书及周年申报支持', '强积金行政指引'], process: ['检查你现有的财务记录', '整理期限和责任分工', '协调所需的专业工作', '让下一个合规节点清楚可见'] } },
  fundingGrants: { en: { name: 'Funding & grants', summary: 'Turn funding opportunities into applications your team can execute.', detail: 'From BUD funding to innovation park support, we help you understand fit, readiness and the work behind an application.', items: ['Funding opportunity and eligibility mapping', 'BUD Fund application preparation', 'Mainland innovation park support review', 'Application documents and execution planning'], process: ['Clarify the business objective', 'Check the fit and eligibility', 'Build the application workplan', 'Coordinate submission and follow-through'] }, 'zh-TW': { name: '資助與基金申請', summary: '把資助機會整理成團隊可以執行的申請計劃。', detail: '由 BUD 基金到內地創新園區支援，協助你了解是否適合、是否準備好，以及申請背後的實際工作。', items: ['資助機會及申請資格整理', 'BUD 基金申請準備', '內地創新園區支援評估', '申請文件及執行規劃'], process: ['釐清企業目標', '確認適用性及申請資格', '建立申請工作計劃', '協調提交及後續跟進'] }, 'zh-CN': { name: '资助与基金申请', summary: '把资助机会整理成团队可以执行的申请计划。', detail: '从 BUD 基金到内地创新园区支持，协助你了解是否适合、是否准备好，以及申请背后的实际工作。', items: ['资助机会及申请资格整理', 'BUD 基金申请准备', '内地创新园区支持评估', '申请文件及执行规划'], process: ['明确企业目标', '确认适用性及申请资格', '建立申请工作计划', '协调提交及后续跟进'] } },
  iang: { en: { name: 'Hong Kong IANG one-stop service', summary: 'A practical landing plan for graduates and professionals building in Hong Kong.', detail: 'A structured one-stop framework for IANG-related planning, company setup, banking, housing and the practical steps around settling into Hong Kong.', items: ['IANG planning and timeline overview', 'Company setup and banking coordination', 'Housing, identity and practical landing referrals', 'Ongoing business support after arrival'], process: ['Understand your background and target', 'Map the IANG and landing timeline', 'Coordinate the selected services', 'Support your next operating step'] }, 'zh-TW': { name: '香港 IANG 一條龍服務', summary: '為畢業生和專業人士準備的香港落地方案。', detail: '以 IANG 規劃、公司成立、銀行開戶、住屋和落地安排為核心，整理在香港開始下一階段所需的實際步驟。', items: ['IANG 規劃及時間線概覽', '公司成立及銀行開戶協調', '住屋、身分及落地轉介', '抵港後的持續商業支援'], process: ['了解你的背景和目標', '整理 IANG 及落地時間線', '協調選定的服務', '支援下一個營運步驟'] }, 'zh-CN': { name: '香港 IANG 一条龙服务', summary: '为毕业生和专业人士准备的香港落地方案。', detail: '以 IANG 规划、公司成立、银行开户、住房和落地安排为核心，整理在香港开始下一阶段所需的实际步骤。', items: ['IANG 规划及时间线概览', '公司成立及银行开户协调', '住房、身份及落地转介', '抵港后的持续商业支持'], process: ['了解你的背景和目标', '整理 IANG 及落地时间线', '协调选定的服务', '支持下一个运营步骤'] } },
  crossBorder: { en: { name: 'Cross-border growth', summary: 'Make expansion across Hong Kong, Mainland China and beyond easier to plan.', detail: 'Connect market entry, business development, resource matching and practical execution into one focused growth plan.', items: ['Market entry and operating model review', 'Cross-border resource and partner matching', 'Business development and expansion planning', 'Execution coordination across stakeholders'], process: ['Define the expansion question', 'Assess markets and resources', 'Build a practical growth route', 'Coordinate the first execution cycle'] }, 'zh-TW': { name: '跨境業務拓展', summary: '讓香港、內地及其他市場的拓展更容易規劃。', detail: '把市場進入、業務發展、資源配對和實際執行，整理成一套聚焦的發展方案。', items: ['市場進入及營運模式檢視', '跨境資源及合作夥伴配對', '業務發展及拓展規劃', '協調各方的執行工作'], process: ['定義拓展問題', '評估市場及資源', '建立實際發展路線', '協調第一個執行週期'] }, 'zh-CN': { name: '跨境业务拓展', summary: '让香港、内地及其他市场的拓展更容易规划。', detail: '把市场进入、业务发展、资源匹配和实际执行，整理成一套聚焦的发展方案。', items: ['市场进入及运营模式检查', '跨境资源及合作伙伴匹配', '业务发展及拓展规划', '协调各方的执行工作'], process: ['定义拓展问题', '评估市场及资源', '建立实际发展路线', '协调第一个执行周期'] } },
  listedCompany: { en: { name: 'Listed company support', summary: 'A structured support layer for companies managing the next phase.', detail: 'Prepare a framework for listed company maintenance, stakeholder coordination, strategic transactions and continued growth.', items: ['Listed company maintenance planning', 'Stakeholder and shareholder coordination', 'M&A and strategic transaction support', 'Pre- and post-IPO financing pathways'], process: ['Understand the company objective', 'Review the current structure', 'Align the relevant advisers and parties', 'Move the agreed workstream forward'] }, 'zh-TW': { name: '上市公司維護支援', summary: '為處理下一階段的上市公司，建立有結構的支援層。', detail: '圍繞上市公司維護、持份者協調、策略交易和持續發展，準備清晰的工作框架。', items: ['上市公司維護規劃', '持份者及股東協調', '併購及策略交易支援', '上市前後融資路線'], process: ['了解企業目標', '檢視現有架構', '協調相關顧問及持份者', '推進已確認的工作範圍'] }, 'zh-CN': { name: '上市公司维护支持', summary: '为处理下一阶段的上市公司，建立有结构的支持层。', detail: '围绕上市公司维护、利益相关方协调、战略交易和持续发展，准备清晰的工作框架。', items: ['上市公司维护规划', '利益相关方及股东协调', '并购及战略交易支持', '上市前后融资路径'], process: ['了解企业目标', '检查现有架构', '协调相关顾问及利益相关方', '推进已确认的工作范围'] } },
};

function Icon({ name, size = 20 }) {
  const paths = {
    arrow: <><path d="M4 12h15" /><path d="m14 6 6 6-6 6" /></>,
    chevron: <path d="m6 9 6 6 6-6" />,
    menu: <><path d="M4 7h16" /><path d="M4 12h16" /><path d="M4 17h16" /></>,
    close: <><path d="m6 6 12 12" /><path d="m18 6-12 12" /></>,
    building: <><path d="M4 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16" /><path d="M16 9h3a2 2 0 0 1 2 2v10" /><path d="M8 7h4M8 11h4M8 15h4M8 19h4M18 15h1M18 19h1" /></>,
    ledger: <><rect x="4" y="3" width="16" height="18" rx="2" /><path d="M8 7h8M8 11h8M8 15h5M8 19h7" /></>,
    spark: <><path d="m12 3 1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3Z" /><path d="m19 16 .6 1.8L21 18.4l-1.4.6L19 21l-.6-2-1.4-.6 1.4-.6L19 16Z" /></>,
    passport: <><rect x="5" y="3" width="14" height="18" rx="2" /><circle cx="12" cy="11" r="3" /><path d="M8 17h8M9 11h6M12 8v6" /></>,
    globe: <><circle cx="12" cy="12" r="9" /><path d="M3 12h18M12 3c2.4 2.5 3.5 5.5 3.5 9s-1.1 6.5-3.5 9c-2.4-2.5-3.5-5.5-3.5-9S9.6 5.5 12 3Z" /></>,
    chart: <><path d="M4 19V5M4 19h16" /><path d="m7 15 3-4 3 2 5-6" /></>,
    check: <path d="m5 12 4 4L19 6" />,
    mail: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m3 7 9 6 9-6" /></>,
    phone: <><path d="M6.5 3.5 9 3l2 5-2.5 1.7a14 14 0 0 0 5.3 5.3l1.7-2.5 5 2 .-5 2.5-1.5c-7.3-1.1-11.4-5.2-12.5-12.5l1.5-1.5Z" /></>,
    map: <><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3-6-3Z" /><path d="M9 3v15M15 6v15" /></>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function routeFor(pathname) {
  const normalized = pathname.replace(/\/$/, '') || '/';
  if (normalized === '/') return { name: 'home' };
  if (normalized === '/services') return { name: 'services' };
  if (normalized.startsWith('/services/')) return { name: 'service', id: normalized.slice('/services/'.length) };
  if (normalized === '/pricing') return { name: 'pricing' };
  if (normalized === '/cases') return { name: 'cases' };
  if (normalized === '/approach') return { name: 'approach' };
  if (normalized === '/about') return { name: 'about' };
  if (normalized === '/contact') return { name: 'contact' };
  if (normalized === '/privacy') return { name: 'privacy' };
  return { name: '404' };
}

function useRoute() {
  const [route, setRoute] = useState(() => routeFor(window.location.pathname));
  useEffect(() => {
    const onPop = () => setRoute(routeFor(window.location.pathname));
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);
  const navigate = (to) => {
    const [path, hash] = to.split('#');
    window.history.pushState({}, '', `${path}${hash ? `#${hash}` : ''}`);
    setRoute(routeFor(path));
    window.scrollTo({ top: 0, behavior: 'auto' });
  };
  return [route, navigate];
}

function ParticleField() {
  const canvasRef = useRef(null);
  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas.getContext('2d');
    let frame;
    let width = 0;
    let height = 0;
    const points = Array.from({ length: 38 }, (_, index) => ({ x: (index * 97) % 1000, y: (index * 53) % 480, vx: (index % 3 - 1) * 0.08, vy: (index % 4 - 2) * 0.04 }));
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const resize = () => { width = canvas.width = canvas.offsetWidth * window.devicePixelRatio; height = canvas.height = canvas.offsetHeight * window.devicePixelRatio; context.setTransform(window.devicePixelRatio, 0, 0, window.devicePixelRatio, 0, 0); width /= window.devicePixelRatio; height /= window.devicePixelRatio; };
    const draw = () => {
      context.clearRect(0, 0, width, height);
      points.forEach((point) => { point.x += reduced ? 0 : point.vx; point.y += reduced ? 0 : point.vy; if (point.x < 0 || point.x > width) point.vx *= -1; if (point.y < 0 || point.y > height) point.vy *= -1; });
      points.forEach((point, index) => points.slice(index + 1).forEach((other) => { const dx = point.x - other.x; const dy = point.y - other.y; const distance = Math.sqrt(dx * dx + dy * dy); if (distance < 145) { context.strokeStyle = `rgba(1, 97, 254, ${0.08 * (1 - distance / 145)})`; context.lineWidth = 1; context.beginPath(); context.moveTo(point.x, point.y); context.lineTo(other.x, other.y); context.stroke(); } }));
      points.forEach((point) => { context.fillStyle = 'rgba(1, 97, 254, .22)'; context.beginPath(); context.arc(point.x, point.y, 1.7, 0, Math.PI * 2); context.fill(); });
      if (!reduced) frame = requestAnimationFrame(draw);
    };
    resize(); draw(); window.addEventListener('resize', resize);
    return () => { cancelAnimationFrame(frame); window.removeEventListener('resize', resize); };
  }, []);
  return <canvas className="particle-field" ref={canvasRef} aria-hidden="true" />;
}

function Header({ t, lang, setLang, navigate, route }) {
  const [open, setOpen] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => {
    if (!mobileOpen) return undefined;
    const closeOnEscape = (event) => { if (event.key === 'Escape') setMobileOpen(false); };
    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', closeOnEscape);
    return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', closeOnEscape); };
  }, [mobileOpen]);
  const go = (to) => { setOpen(false); setMobileOpen(false); navigate(to); };
  const isActive = (name) => route.name === name || (name === 'services' && route.name === 'service');
  return <>
    <header className="site-header">
      <div className="header-inner">
        <button className="brand" type="button" onClick={() => go('/')} aria-label="WINFO home"><img src="/WINFO-blue.png" alt="WINFO" /><span>{t.brand}</span></button>
        <nav className="desktop-nav" aria-label="Primary navigation">
          <div className="nav-menu-shell" onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} onFocus={() => setOpen(true)} onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setOpen(false); }}>
            <button type="button" className={`nav-link nav-services ${open ? 'is-open' : ''} ${isActive('services') ? 'is-active' : ''}`} aria-expanded={open} aria-controls="services-mega-menu" onClick={() => go('/services')}>{t.nav.services}<Icon name="chevron" size={15} /></button>
            <div id="services-mega-menu" className={`mega-menu ${open ? 'is-open' : ''}`}>
              <div className="mega-grid"><div><span className="menu-label">{t.menu.start}</span>{serviceItems.filter((item) => item.group === 'start').map((item) => <ServiceMenuLink key={item.id} item={item} t={t} lang={lang} go={go} />)}</div><div><span className="menu-label">{t.menu.compliance}</span>{serviceItems.filter((item) => item.group === 'compliance').map((item) => <ServiceMenuLink key={item.id} item={item} t={t} lang={lang} go={go} />)}</div><div><span className="menu-label">{t.menu.grow}</span>{serviceItems.filter((item) => item.group === 'grow').map((item) => <ServiceMenuLink key={item.id} item={item} t={t} lang={lang} go={go} />)}</div><div className="mega-aside"><span>{t.menu.support}</span><button type="button" onClick={() => go('/contact')}>{t.menu.talk}<Icon name="arrow" size={16} /></button></div></div>
              <div className="mega-footer"><button type="button" onClick={() => go('/services')}>{t.menu.explore}<Icon name="arrow" size={16} /></button><span>WINFO / 01</span></div>
            </div>
          </div>
          <button type="button" className={`nav-link ${isActive('pricing') ? 'is-active' : ''}`} onClick={() => go('/pricing')}>{t.nav.pricing}</button><button type="button" className={`nav-link ${isActive('cases') ? 'is-active' : ''}`} onClick={() => go('/cases')}>{t.nav.cases}</button><button type="button" className={`nav-link ${isActive('approach') ? 'is-active' : ''}`} onClick={() => go('/approach')}>{t.nav.approach}</button><button type="button" className={`nav-link ${isActive('about') ? 'is-active' : ''}`} onClick={() => go('/about')}>{t.nav.about}</button><button type="button" className={`nav-link ${isActive('contact') ? 'is-active' : ''}`} onClick={() => go('/contact')}>{t.nav.contact}</button>
        </nav>
        <div className="header-actions"><div className="language-switcher" aria-label="Language switcher">{languages.map((item) => <button key={item.code} type="button" className={lang === item.code ? 'is-active' : ''} onClick={() => setLang(item.code)}>{item.label}</button>)}</div><button type="button" className="header-cta" onClick={() => go('/contact')}>{t.nav.cta}<Icon name="arrow" size={16} /></button><button type="button" className="mobile-toggle" onClick={() => setMobileOpen(true)} aria-label={t.nav.menu}><Icon name="menu" size={22} /></button></div>
      </div>
    </header>
    {mobileOpen && <div className="mobile-menu" role="dialog" aria-modal="true" aria-label={t.nav.menu}><div className="mobile-menu-head"><button className="brand" type="button" onClick={() => go('/')}><img src="/WINFO-blue.png" alt="WINFO" /><span>{t.brand}</span></button><button type="button" className="mobile-close" onClick={() => setMobileOpen(false)} aria-label={t.nav.close}><Icon name="close" size={22} /></button></div><div className="mobile-menu-scroll"><button type="button" className="mobile-nav-link" onClick={() => go('/services')}>{t.nav.services}<Icon name="arrow" size={17} /></button>{serviceItems.map((item) => <button type="button" className="mobile-service-link" key={item.id} onClick={() => go(`/services/${item.id}`)}><Icon name={item.icon} size={18} /><span>{serviceContent[item.key][lang].name}</span><Icon name="arrow" size={15} /></button>)}<button type="button" className="mobile-nav-link" onClick={() => go('/pricing')}>{t.nav.pricing}<Icon name="arrow" size={17} /></button><button type="button" className="mobile-nav-link" onClick={() => go('/cases')}>{t.nav.cases}<Icon name="arrow" size={17} /></button><button type="button" className="mobile-nav-link" onClick={() => go('/approach')}>{t.nav.approach}<Icon name="arrow" size={17} /></button><button type="button" className="mobile-nav-link" onClick={() => go('/about')}>{t.nav.about}<Icon name="arrow" size={17} /></button><button type="button" className="mobile-nav-link" onClick={() => go('/contact')}>{t.nav.contact}<Icon name="arrow" size={17} /></button></div><div className="mobile-menu-footer"><div className="language-switcher">{languages.map((item) => <button key={item.code} type="button" className={lang === item.code ? 'is-active' : ''} onClick={() => setLang(item.code)}>{item.label}</button>)}</div><button type="button" className="header-cta" onClick={() => go('/contact')}>{t.nav.cta}<Icon name="arrow" size={16} /></button></div></div>}
  </>;
}

function ServiceMenuLink({ item, t, lang, go }) { const title = serviceContent[item.key][lang].name; return <button type="button" className="mega-service-link" onClick={() => go(`/services/${item.id}`)}><span className="menu-icon"><Icon name={item.icon} size={18} /></span><span><strong>{title}</strong><small>{item.group === 'start' ? t.menu.start : item.group === 'grow' ? t.menu.grow : t.menu.compliance}</small></span><Icon name="arrow" size={15} /></button>; }

function ServiceCard({ item, lang, t, navigate }) { const service = serviceContent[item.key][lang]; return <button type="button" className="service-card" onClick={() => navigate(`/services/${item.id}`)}><span className="service-card-top"><span className="service-icon"><Icon name={item.icon} size={22} /></span><span className="service-index">0{serviceItems.indexOf(item) + 1}</span></span><span className="service-card-title">{service.name}</span><span className="service-card-body">{service.summary}</span><span className="service-card-link">{t.services.path}<Icon name="arrow" size={15} /></span></button>; }

function ServiceFinder({ lang, navigate }) { const [selectedId, setSelectedId] = useState('company-setup'); const labels = finderCopy[lang]; const selectedOption = finderOptions.find((option) => option.id === selectedId) || finderOptions[0]; const selectedItem = serviceItems.find((item) => item.id === selectedOption.id); const selectedService = serviceContent[selectedItem.key][lang]; return <section className="section service-finder-section"><div className="content-width service-finder"><div className="finder-heading"><div className="eyebrow"><span className="eyebrow-dot" />WINFO / FIND YOUR STARTING POINT</div><h2>{labels.title}</h2><p>{labels.body}</p></div><div className="finder-content"><div className="finder-options">{labels.options.map((label, index) => <button type="button" key={label} className={selectedOption.key === finderOptions[index].key ? 'is-active' : ''} aria-pressed={selectedId === finderOptions[index].id} onClick={() => setSelectedId(finderOptions[index].id)}><span>0{index + 1}</span><strong>{label}</strong><Icon name="arrow" size={16} /></button>)}</div><div className="finder-result"><span>{labels.result}</span><h3>{selectedService.name}</h3><p>{selectedService.summary}</p><button type="button" className="button button-primary" onClick={() => navigate(`/services/${selectedItem.id}`)}>{labels.cta}<Icon name="arrow" size={16} /></button></div></div></div></section>; }

function HomePage({ t, lang, navigate }) { return <main>
  <section className="hero-section"><ParticleField /><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" />WINFO / BUSINESS SOLUTIONS</div><h1>{t.hero.title}</h1><p>{t.hero.body}</p><div className="hero-actions"><button type="button" className="button button-primary" onClick={() => navigate('/contact')}>{t.hero.primary}<Icon name="arrow" size={17} /></button><button type="button" className="text-button" onClick={() => navigate('/services')}>{t.hero.secondary}<Icon name="arrow" size={17} /></button></div><span className="hero-note">{t.hero.note}</span></div><div className="hero-visual"><div className="hero-image-wrap"><img src="/Main_banner.jpg" alt="Hong Kong skyline at night" /><div className="hero-image-shade" /></div><div className="hero-info-card"><span>{t.hero.visualLabel}</span><strong>{t.hero.visualTitle}</strong><p>{t.hero.visualText}</p><button type="button" onClick={() => navigate('/approach')}>{t.nav.approach}<Icon name="arrow" size={15} /></button></div><div className="hero-coordinate">22.3193° N<br />114.1694° E</div></div></div><div className="hero-bottom"><span>01 / 05</span><div className="hero-rule"><i /></div><span>Hong Kong · Cross-border</span></div></section>
  <section className="proof-strip"><div className="content-width proof-inner"><span className="proof-label">WINFO SUPPORTS</span>{t.proof.map((item) => <span key={item} className="proof-item"><i /><span>{item}</span></span>)}</div></section>
  <section className="section services-preview"><div className="content-width"><div className="section-heading split-heading"><div><div className="eyebrow"><span className="eyebrow-dot" />{t.home.servicesKicker}</div><h2>{t.home.servicesTitle}</h2></div><div className="heading-side"><p>{t.home.servicesBody}</p><button type="button" className="text-button" onClick={() => navigate('/services')}>{t.home.viewAll}<Icon name="arrow" size={17} /></button></div></div><div className="service-grid">{serviceItems.slice(0, 4).map((item) => <ServiceCard key={item.id} item={item} lang={lang} t={t} navigate={navigate} />)}</div></div></section>
  <ServiceFinder lang={lang} navigate={navigate} />
  <section className="section blue-band"><div className="content-width blue-band-grid"><div><div className="eyebrow eyebrow-light"><span className="eyebrow-dot" />{t.home.whyKicker}</div><h2>{t.home.whyTitle}</h2></div><div><p>{t.home.whyBody}</p><ul className="check-list">{t.home.principles.map((item) => <li key={item}><Icon name="check" size={17} />{item}</li>)}</ul><button type="button" className="button button-white" onClick={() => navigate('/approach')}>{t.nav.approach}<Icon name="arrow" size={17} /></button></div></div></section>
  <section className="section cases-preview"><div className="content-width"><div className="section-heading split-heading"><div><div className="eyebrow"><span className="eyebrow-dot" />{t.home.casesKicker}</div><h2>{t.home.casesTitle}</h2></div><div className="heading-side"><p>{t.home.casesBody}</p><button type="button" className="text-button" onClick={() => navigate('/cases')}>{t.home.casesButton}<Icon name="arrow" size={17} /></button></div></div><div className="case-feature"><div className="case-feature-number">01</div><div><span className="case-kicker">WINFO / OPERATING CLARITY</span><h3>Make the next business decision easier to own.</h3><p>{t.home.quote}</p><span className="case-by">{t.home.quoteBy}</span></div><div className="case-feature-mark"><span>→</span><small>EXPLORE<br />THE METHOD</small></div></div></div></section>
  <section className="section final-cta"><div className="content-width final-cta-inner"><div><div className="eyebrow"><span className="eyebrow-dot" />WINFO / NEXT STEP</div><h2>{t.home.finalTitle}</h2><p>{t.home.finalBody}</p></div><button type="button" className="button button-primary" onClick={() => navigate('/contact')}>{t.home.finalButton}<Icon name="arrow" size={17} /></button></div></section>
 </main>; }

function ServicesPage({ t, lang, navigate }) { const featured = serviceContent.iang[lang]; return <PageShell className="services-page"><PageIntro kicker={t.services.kicker} title={t.services.title} body={t.services.body} /><section className="content-width featured-service"><div className="featured-service-copy"><span className="eyebrow"><span className="eyebrow-dot" />{t.services.featured}</span><h2>{t.services.iangTitle}</h2><p>{t.services.iangBody}</p><button type="button" className="button button-primary" onClick={() => navigate('/services/iang')}>{t.services.path}<Icon name="arrow" size={17} /></button></div><div className="featured-service-art"><ParticleField /><div className="art-code">HKG<br />IANG<br />01</div><div className="art-orbit" /></div></section><section className="section services-all"><div className="content-width"><div className="eyebrow"><span className="eyebrow-dot" />{t.services.all}</div><div className="service-grid service-grid-six">{serviceItems.map((item) => <ServiceCard key={item.id} item={item} lang={lang} t={t} navigate={navigate} />)}</div></div></section></PageShell>; }

function PageShell({ children, className = '' }) { return <main className={className}>{children}</main>; }
function PageIntro({ kicker, title, body }) { return <section className="page-intro"><div className="content-width page-intro-inner"><div className="eyebrow"><span className="eyebrow-dot" />{kicker}</div><h1>{title}</h1><p>{body}</p></div></section>; }

function ServicePage({ t, lang, id, navigate }) { const item = serviceItems.find((service) => service.id === id); const content = item ? serviceContent[item.key][lang] : null; if (!content) return <NotFoundPage t={t} navigate={navigate} />; return <PageShell className="service-detail-page"><section className="page-intro service-detail-intro"><div className="content-width"><button type="button" className="back-link" onClick={() => navigate('/services')}><span>←</span>{t.servicePage.back}</button><div className="service-detail-layout"><div><div className="service-icon large"><Icon name={item.icon} size={28} /></div><div className="eyebrow"><span className="eyebrow-dot" />{t.servicePage.overview}</div><h1>{content.name}</h1><p>{content.summary}</p></div><div className="detail-note"><span>WINFO / {String(serviceItems.indexOf(item) + 1).padStart(2, '0')}</span><p>{content.detail}</p></div></div></div></section><section className="section detail-content"><div className="content-width detail-grid"><div><div className="eyebrow"><span className="eyebrow-dot" />{t.servicePage.included}</div><ul className="included-list">{content.items.map((entry) => <li key={entry}><Icon name="check" size={18} /><span>{entry}</span></li>)}</ul></div><div><div className="eyebrow"><span className="eyebrow-dot" />{t.servicePage.process}</div><div className="process-list">{content.process.map((entry, index) => <div className="process-row" key={entry}><span>{String(index + 1).padStart(2, '0')}</span><strong>{entry}</strong></div>)}</div></div></div></section><section className="section detail-placeholder"><div className="content-width placeholder-box"><span className="placeholder-line" /><p>{t.servicePage.placeholder}</p><span className="placeholder-line short" /></div></section><section className="section detail-cta"><div className="content-width detail-cta-inner"><div><h2>{t.servicePage.ready}</h2><p>{t.servicePage.readyBody}</p></div><button type="button" className="button button-primary" onClick={() => navigate('/contact')}>{t.servicePage.enquire}<Icon name="arrow" size={17} /></button></div></section></PageShell>; }

function PricingPage({ t, navigate }) { return <PageShell className="pricing-page"><PageIntro kicker={t.pricing.kicker} title={t.pricing.title} body={t.pricing.body} /><section className="section pricing-section"><div className="content-width"><div className="pricing-grid">{t.pricing.plans.map((plan) => <div className={`pricing-plan ${plan.featured ? 'is-featured' : ''}`} key={plan.name}>{plan.featured && <span className="featured-label">RECOMMENDED</span>}<span className="plan-index">0{t.pricing.plans.indexOf(plan) + 1}</span><h2>{plan.name}</h2><p>{plan.desc}</p><ul className="check-list dark">{plan.items.map((item) => <li key={item}><Icon name="check" size={16} />{item}</li>)}</ul><button type="button" className={plan.featured ? 'button button-primary' : 'text-button'} onClick={() => navigate('/contact')}>{plan.action}<Icon name="arrow" size={16} /></button></div>)}</div><p className="pricing-note">{t.pricing.note}</p></div></section></PageShell>; }

function CasesPage({ t }) { const [filter, setFilter] = useState(t.cases.filters[0]); const projects = filter === t.cases.filters[0] ? t.cases.projects : t.cases.projects.filter((item) => item.type === filter); return <PageShell className="cases-page"><PageIntro kicker={t.cases.kicker} title={t.cases.title} body={t.cases.body} /><section className="section cases-section"><div className="content-width"><div className="filter-row" role="tablist">{t.cases.filters.map((item) => <button type="button" role="tab" aria-selected={filter === item} className={filter === item ? 'is-active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="case-list">{projects.map((project, index) => <article className="case-row" key={project.title}><span className="case-row-number">{String(index + 1).padStart(2, '0')}</span><div><span className="case-kicker">{project.type}</span><h2>{project.title}</h2><p>{project.body}</p></div><div className="case-result"><span>RESULT</span><strong>{project.result}</strong></div></article>)}</div></div></section></PageShell>; }

function ApproachPage({ t }) { return <PageShell className="approach-page"><PageIntro kicker={t.approach.kicker} title={t.approach.title} body={t.approach.body} /><section className="section approach-section"><div className="content-width approach-list">{t.approach.steps.map((step) => <article className="approach-step" key={step.n}><span className="step-number">{step.n}</span><div><h2>{step.title}</h2><p>{step.body}</p></div><span className="step-arrow">↘</span></article>)}</div></section></PageShell>; }

function AboutPage({ t }) { return <PageShell className="about-page"><PageIntro kicker={t.about.kicker} title={t.about.title} body={t.about.body} /><section className="section about-stats"><div className="content-width stats-grid">{t.about.stats.map((stat) => <div className="stat" key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></section><section className="section values-section"><div className="content-width values-grid"><div><div className="eyebrow"><span className="eyebrow-dot" />WINFO / VALUES</div><h2>{t.about.valuesTitle}</h2></div><ul className="number-list">{t.about.values.map((value, index) => <li key={value}><span>0{index + 1}</span><p>{value}</p></li>)}</ul></div></section></PageShell>; }

function ContactPage({ t }) { const [sent, setSent] = useState(false); const [form, setForm] = useState({ name: '', email: '', company: '', message: '' }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); return <PageShell className="contact-page"><PageIntro kicker={t.contact.kicker} title={t.contact.title} body={t.contact.body} /><section className="section contact-section"><div className="content-width contact-grid"><div className="contact-details"><span className="eyebrow"><span className="eyebrow-dot" />{t.contact.detailsTitle}</span><a href={`mailto:${t.contact.email}`}><Icon name="mail" size={18} />{t.contact.email}</a><a href={`tel:${t.contact.phone.replace(/\s/g, '')}`}><Icon name="phone" size={18} />{t.contact.phone}</a><p><Icon name="map" size={18} />{t.contact.address}</p><span className="hours">{t.contact.hours}</span></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label>{t.contact.form.name}<input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder={t.contact.form.name} /></label><label>{t.contact.form.email}<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} placeholder={t.contact.form.email} /></label><label>{t.contact.form.company}<input value={form.company} onChange={(event) => update('company', event.target.value)} placeholder={t.contact.form.company} /></label><label>{t.contact.form.message}<textarea required value={form.message} onChange={(event) => update('message', event.target.value)} placeholder={t.contact.form.message} rows="5" /></label><button type="submit" className="button button-primary">{sent ? t.contact.form.success : t.contact.form.send}<Icon name={sent ? 'check' : 'arrow'} size={17} /></button></form></div></section></PageShell>; }

function PrivacyPage({ t }) { return <PageShell className="privacy-page"><PageIntro kicker={t.privacy.kicker} title={t.privacy.title} body={t.privacy.intro} /><section className="section privacy-section"><div className="content-width privacy-layout"><aside><span>{t.privacy.updated}</span><a href="mailto:enquiry@winfo.hk">enquiry@winfo.hk</a></aside><div className="privacy-copy">{t.privacy.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}</div></div></section></PageShell>; }
function NotFoundPage({ t, navigate }) { return <PageShell className="not-found-page"><section className="page-intro"><div className="content-width not-found"><div className="eyebrow"><span className="eyebrow-dot" />{t.notFound.kicker}</div><h1>{t.notFound.title}</h1><p>{t.notFound.body}</p><div className="hero-actions"><button type="button" className="button button-primary" onClick={() => navigate('/')}>{t.notFound.home}<Icon name="arrow" size={17} /></button><button type="button" className="text-button" onClick={() => navigate('/contact')}>{t.notFound.contact}<Icon name="arrow" size={17} /></button></div></div></section></PageShell>; }

function Footer({ t, navigate }) { return <footer className="site-footer"><div className="content-width footer-main"><div className="footer-brand"><button className="brand" type="button" onClick={() => navigate('/')}><img src="/WINFO-blue.png" alt="WINFO" /><span>{t.brand}</span></button><p>{t.footer.line}</p></div><div className="footer-columns"><div><span>{t.footer.services}</span><button type="button" onClick={() => navigate('/services')}>{t.nav.services}</button><button type="button" onClick={() => navigate('/pricing')}>{t.nav.pricing}</button><button type="button" onClick={() => navigate('/cases')}>{t.nav.cases}</button></div><div><span>{t.footer.company}</span><button type="button" onClick={() => navigate('/about')}>{t.nav.about}</button><button type="button" onClick={() => navigate('/approach')}>{t.nav.approach}</button><button type="button" onClick={() => navigate('/contact')}>{t.nav.contact}</button></div><div><span>{t.footer.legal}</span><button type="button" onClick={() => navigate('/privacy')}>{t.footer.privacy}</button><a href="mailto:enquiry@winfo.hk">enquiry@winfo.hk</a><a href="tel:+85266515286">+852 6651 5286</a></div></div></div><div className="content-width footer-bottom"><span>© {new Date().getFullYear()} {t.footer.copyright}</span><span>HONG KONG / WINFO</span></div></footer>; }

function App() { const [route, navigate] = useRoute(); const [lang, setLang] = useState(() => window.localStorage.getItem('winfo-language') || 'en'); const t = useMemo(() => copy[lang] || copy.en, [lang]); useEffect(() => { window.localStorage.setItem('winfo-language', lang); document.documentElement.lang = lang === 'en' ? 'en' : lang === 'zh-TW' ? 'zh-Hant' : 'zh-Hans'; document.title = route.name === 'home' ? 'WINFO | Business Solutions in Hong Kong' : `${route.name === '404' ? 'Page not found' : route.name[0].toUpperCase() + route.name.slice(1)} | WINFO`; }, [lang, route]); let content; if (route.name === 'home') content = <HomePage t={t} lang={lang} navigate={navigate} />; else if (route.name === 'services') content = <ServicesPage t={t} lang={lang} navigate={navigate} />; else if (route.name === 'service') content = <ServicePage t={t} lang={lang} id={route.id} navigate={navigate} />; else if (route.name === 'pricing') content = <PricingPage t={t} navigate={navigate} />; else if (route.name === 'cases') content = <CasesPage t={t} />; else if (route.name === 'approach') content = <ApproachPage t={t} />; else if (route.name === 'about') content = <AboutPage t={t} />; else if (route.name === 'contact') content = <ContactPage t={t} />; else if (route.name === 'privacy') content = <PrivacyPage t={t} />; else content = <NotFoundPage t={t} navigate={navigate} />; return <div className="site-shell"><Header t={t} lang={lang} setLang={setLang} navigate={navigate} route={route} />{content}<Footer t={t} navigate={navigate} /></div>; }

createRoot(document.getElementById('root')).render(<App />);
